### ISSUE TITLE
"Add-on Startup Failed" after newest update

### ISSUE THREAD

**Issue by jebra102** [Robin-Haupt-1/Auto-Sync-Anki-Addon#12]
Hey, I just wanted to bring this up, since I didn't see anything in the issues referring to this.

The update came up today as I was opening Anki, so I restarted Anki, the usual.
Immediately when I opened it again, I got the following problem:
Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 5.15.2 PyQt 5.15.5
Platform: Windows-10-10.0.22631
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-11-21 12:35:49

When loading Auto Sync:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "C:\Users\Jeane\AppData\Roaming\Anki2\addons21\501542723\__init__.py", line 1, in <module>
    from . import  main
  File "C:\Users\Jeane\AppData\Roaming\Anki2\addons21\501542723\main.py", line 4, in <module>
    from .options_dialog import on_options_call
  File "C:\Users\Jeane\AppData\Roaming\Anki2\addons21\501542723\options_dialog.py", line 1, in <module>
    from PyQt6 import QtGui
ModuleNotFoundError: No module named 'PyQt6'

From what I can tell, it is still working? Is it due to me not being on Qt6?

**Comment by Robin-Haupt-1** [comment]
Yes, this seems to be since you're using the PyQt5 version of Anki. I've removed compatibility with that since the addon had stopped working on the PyQt6 build of Anki.

**Comment by jebra102** [comment]
Got it. Thanks for the reply.
I'll sadly have to stick to it for a little longer, since some other Add-ons don't seem to work on Qt6 for me. So I'll disable it for the time being. That seems to deal with the annoying pop up upon booting up Anki.
It also did not Auto-sync, at least for me, but it did give me the usual pop ups.
